config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :flights, only: %i[index]
  resources :bookings, only: %i[new create show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :code, presence: true, uniqueness: true

  has_many :arriving_flights,
           class_name: Flight.name,
           foreign_key: :arrival_airport_id,
           dependent: :destroy
  has_many :departing_flights,
           class_name: Flight.name,
           foreign_key: :departure_airport_id,
           dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight, required: true
  has_many :passenger_bookings
  has_many :passengers, through: :passenger_bookings, inverse_of: :bookings

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :start, :duration, presence: true

  belongs_to :departure_airport, class_name: Airport.name, required: true
  belongs_to :arrival_airport, class_name: Airport.name, required: true
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :passenger_bookings
  has_many :bookings, through: :passenger_bookings, inverse_of: :passengers
  has_many :flights, through: :bookings
end

app/models/passenger_booking.rb
class PassengerBooking < ApplicationRecord
  belongs_to :booking, required: true
  belongs_to :passenger, required: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    params[:passengers_count].to_i.times { @booking.passengers.build }
    @flight = Flight.find(params[:booking_option])
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      PassengerMailer.with(booking_id: @booking.id).confirmation_email.deliver_now
      redirect_to booking_path(@booking), notice: 'Booking has been successfully created!'
    else
      @flight = @booking.flight
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
  end

  private

  def booking_params
    params.require(:booking)
          .permit(:flight_id,
                  passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |a| [a.code, a.id] }
    @start_flight_options = Flight.order(:start).map { |f| [f.start.strftime('%d/%m/%Y'), f.start] }.uniq

    return if search_params.empty?

    @booking_options = Flight.where(start: search_params[:start],
                                    arrival_airport_id: search_params[:arrival_airport_id],
                                    departure_airport_id: search_params[:departure_airport_id])

  end

  def search_params
    params.permit(:departure_airport_id,
                  :arrival_airport_id,
                  :passengers_count,
                  :start)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= form_with model: booking do |f| %>
  <%= f.hidden_field :flight_id, value: params[:booking_option] %>

  <%= f.fields_for :passengers do |passenger_form| %>
    <div class="new-passenger-container">
      <div class="form-field">
        <%= passenger_form.label :name %>
        <%= passenger_form.text_field :name,
                                      required: true,
                                      placeholder: "Passenger's name" %>
      </div>

      <div class="form-field">
        <%= passenger_form.label :email %>
        <%= passenger_form.email_field :email,
                                       required: true,
                                       placeholder: "abc@com.ua" %>
      </div>
    </div>
  <% end %>

  <div class="form-button">
    <%= f.submit "Finalize Booking" %>
  </div>
<% end %>

app/views/bookings/new.html.erb
<div class="new-booking-container">
  <p class="sub-title">Flight Information:</p>
  <%= "From: #{@flight.departure_airport.code}, To: #{@flight.arrival_airport.code}, Duration: #{@flight.duration}, Start: #{@flight.start}"%>

  <br />

  <p class="sub-title">Add Passenger(s) Info:</p>
  <%= render 'form', booking: @booking %>
</div>

app/views/bookings/show.html.erb
<div class="booking-section-container">
  <div class="booking-section-title">
    <p class="sub-title">
      <%= pluralize(@booking.passengers.count, "Passenger") %>:
    </p>
  </div>
  <div class="booking-section-summary">
    <% @booking.passengers.each do |passenger| %>
      <p>
        Name: <%= passenger.name %>
      </p>
      <p>
        Email: <%= passenger.email %>
      </p>
    <% end %>
  </div>
</div>
<br />
<div class="booking-section-container">
  <div class="booking-section-title">
    <p class="sub-title">
      Flight Information:
    </p>
  </div>
  <div class="booking-section-summary">
    <%= "From: #{@flight.departure_airport.code}, To: #{@flight.arrival_airport.code}, Duration: #{@flight.duration}, Start: #{@flight.start}"%>
  </div>
</div>

app/views/flights/_results_selection_form.html.erb
<%= form_with url: new_booking_path, method: :get do |f| %>
  <%= f.hidden_field :passengers_count, value: params[:passengers_count] %>

  <div class="radio-button-container">
    <% @booking_options.each do |booking| %>
      <div class="form-field">
        <%= f.radio_button :booking_option, booking.id, { required: true } %>
        <%= f.label :booking_option, for: "booking_option_#{booking.id}" do %>
          <%= "From: #{booking.departure_airport.code}, To: #{booking.arrival_airport.code}, Duration: #{booking.duration}, Start: #{booking.start}"%>
        <% end %>
      </div>
    <% end %>
  </div>

  <% if @booking_options.empty? %>
    <p>Sorry, no flights match your search criteria. Please choose a date within the next 30 days.</p>
  <% else %>
    <div class="form-button">
      <%= f.submit "Book Flight" %>
    </div>
  <% end %>
<% end %>

app/views/flights/_search_form.html.erb
<%= form_with url: flights_path, method: :get do |f| %>
  <div class="form-field">
    <%= f.label "Departure Airport" %>
    <%= f.select(:departure_airport_id,
                 options_for_select(@airport_options, params[:departure_airport_id]),
                 required: true ) %>
  </div>

  <div class="form-field">
    <%= f.label "Arrival Airport" %>
    <%= f.select(:arrival_airport_id,
                 options_for_select(@airport_options, params[:arrival_airport_id]),
                 required: true ) %>
  </div>

  <div class="form-field">
    <%= f.label "Number Of Passengers" %>
    <%= f.select(:passengers_count,
                 options_for_select([1, 2, 3, 4], params[:passenger_count]),
                 required: true ) %>
  </div>

  <div class="form-field">
    <%= f.label "Flight Start" %>
    <%= f.select(:start,
                 options_for_select(@start_flight_options, params[:start]),
                 required: true ) %>
  </div>

  <div class="form-button">
    <%= f.submit "Find Flights" %>
  </div>
<% end %>

app/views/flights/index.html.erb
<div class="flight-container">
  <%= render 'search_form' %>

  <div class="flight-results">
    <% if @booking_options %>
      <p class="sub-title">Available Flights:</p>
      <%= render 'results_selection_form' %>
    <% else %>
      <p class="results-placeholder">Choose flight options to see the available flights.</p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>